class RegistrationFields:
    repository = 'repository'
    job = 'job'
    labels = 'labels'
    requested_params = 'requested_params'
    branch_restrictions = 'branch_restrictions'
    change_restrictions = 'change_restrictions'
    file_restrictions = 'file_restrictions'
    missed_times = 'missed_times'
    jenkins_url = 'jenkins_url'
